### PR TITLE
Add environment variables for all config keys

### PR DESCRIPTION
**Pull request by rh072005**
I've configured my ghost instance using a combination of defaults and environment variables up to now but haven't been able to set the CDN url this way.
To get around that I've added support for setting this via an environment variable and also added the other keys in at the same time

### CODE REVIEW

**Comment by jldeen** [comment]
Stale pull request message

**Comment by rh072005** [comment]
@jldeen - any thoughts on the usefulness of this?

**Comment by Amoenus** [comment]
I believe this is useful. Was trying to set the variables for storage but it's not possible due to the illegal character '-'. An ability to set those value directly on the environment would be useful

image

**Comment by rh072005** [comment]
@Amoenus - that's the exact issue I ran into that led me to add the extra variables

**Comment by jldeen** [comment]
Apologies for the delay. I will review this PR this week and merge if it looks good. Also, I want to have better docs if there is an error when you do attempt to add env var. I am using this adapter in my own blog and I have not seen this error message. Will report back shortly. Thanks for this PR!

**Comment by rh072005** [comment]
I think the error only comes up when you try and add the config via environment variables using Azure Web App config settings. I don't think it would be an issue when using the config files.

**Comment by Amoenus** [comment]
@jldeen any specific reason this got rejected. Was looking forward to this change, so that I could set all of my configurations via Azure Portal.

**Comment by rh072005** [comment]
@jldeen - Am I right in thinking this was autoclosed? If not is there any changes needed?

**Pull request closed without merging**
